# Generated by Django 2.2.6 on 2022-04-07 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20220404_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='order_mount',
            new_name='order_amount',
        ),
    ]
